### ISSUE TITLE
Cache or run j4-dmenu-desktop on startup to be able to run it immediately after I open my window manager 

### ISSUE THREAD

**Issue by antaxiom** [enkore/j4-dmenu-desktop#102]
I've been using `j4-dmenu-desktop` for a long time now but I notice when I fresh boot my system it takes a bit (maybe a 1-3 seconds) to startup, to my understanding this is because it's looking at all my .desktop files and caching them. 
If there's some kind of method to make it do this on startup (without actually running it) that would be great as I wouldn't have to wait for it on first boots anymore. Sorry if I missed something and thanks to anyone who help

**Comment by enkore** [comment]
Give --wait-on mode a shot:

```
--wait-on=<path>
    Must point to a path where a file can be created.
    In this mode no menu will be shown. Instead the program waits for <path>
    to be written to (use echo > path). Every time this happens a menu will be shown.
    Desktop files are parsed ahead of time.
    Perfoming 'echo -n q > path' will exit the program.
```

You basically do "j4-dmenu-desktop --wait-on ~/.something ..." in your auto start and then use "echo > ~/.something" to get a menu.

The caching you mention isn't done by j4dd itself, but it's just the operating system pagecache. So you may alternatively do "j4dd --no-exec --dmenu=echo", just to have it read all the files once to get them cached.

Considering it takes a few seconds for you I assume you are using a hard drive? If so, just upgrading j4dd to the current git version might already help, since I recently added an optimization for hard drives.

**Comment by antaxiom** [comment]
The first solution isn't super viable for me as I hate having to add prefixes to my already lengthy commands, initially the second one didn't seem to work until I updated but it doesn't give me an error so I assume it works, same for the hard drive optimization (I'm getting an SSD soon). I can't restart at the moment but I'm sure it will work! Thanks for the response, you're an awesome dev!

**Comment by antaxiom** [comment]
I'll close this after proving it works

**Comment by antaxiom** [comment]
Just tested, works like a charm! Thanks a bunch!

**Comment by enkore** [comment]
Thanks, glad you like it!
