### ISSUE TITLE
Bind to key

### ISSUE THREAD

**Issue by link2xt** [enkore/j4-dmenu-desktop#103]
I am using a slow HDD, so when .desktop files are evicted from filesystem cache, starting `j4-dmenu-desktop` takes seconds.

Issue #102 contains a solution, using `--wait-on=`. But writing to the created pipe requires running some program that will write to the file, which is hard to do from `dwm` config. Of course I can write a C function to do it, but it looks hacky.

How about adding an option to listen for keyboard events, like [sxhkd](https://github.com/baskerville/sxhkd) or xbindkeys do, and bypass all the pipe creation, writing and reading? Then it will be enough to start `j4-dmenu-desktop --bind=super+p` from `xinitrc` regardless of the window manager used.

**Comment by enkore** [comment]
Currently j4dd doesn't contain any window-system specific code at all. It reads files and creates processes. This is very portable and doesn't require any extra libraries.

Listening for keystrokes would require at least separate X11 and Wayland implementations, so that's a lot of work. j4dd was originally made for use from i3, which supports arbitrary keybindings (like most tiling WMs). Full desktops also generally have a mechanism for global shortcuts to e.g. launch a script. Maybe there's a panel that you can use to make a shortcut.
