### ISSUE TITLE
Performance: The inbuilt replace function can be improve

### ISSUE THREAD

**Issue by Hritik14** [enkore/j4-dmenu-desktop#105]
The current replace function looks like this
```
inline std::string &replace(std::string &str, const std::string &substr, const std::string &substitute)
{
    if(substr.empty())
        return str;
    size_t start_pos = 0;
    while((start_pos = str.find(substr, start_pos)) != std::string::npos) {
        str.replace(start_pos, substr.length(), substitute);
        start_pos += substitute.length();
    }
    return str;
}
```

This as simple as one could think. Though, it creates a new copy of the string on each iteration. I thin that is unnecessary. 
Instead, we could predetermine the final string size and create a string of that size. Then we may iterate over the main string, copy each char until we hit a `std::string::find`, copy the substitute and proceed.

I could work on implementing this if desired.

**Comment by enkore** [comment]
You are correct, but this function isn't used much and most of the issue goes away because std::string amortizes growth operations (e.g. when you add a byte to a string that's full (size==capacity), it will grow by say 50 % instead of just the one byte). I don't think it'd be worth the effort to optimize this, but good find and thanks for the offer! :)
