### ISSUE TITLE
Honor $XDG_DATA_DIRS

### ISSUE THREAD

**Issue by Lykos153** [enkore/j4-dmenu-desktop#114]
Desktop applications installed via [nix](https://nixos.org) on a per-user basis are currently not found. I have `XDG_DATA_DIRS` set to `$HOME/.nix-profile/share` but j4-dmenu-desktop doesn't see it. I can set `XDG_DATA_HOME` to this path but then I lose access to the apps in `.local/share/applications`. Currently I'm helping myself with symlinks, but it would be great if j4-dmenu-desktop supported this variable.

> $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'. 
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by muni-corn** [comment]
I'm not the most familiar with the code here but is this [already implemented?](https://github.com/enkore/j4-dmenu-desktop/blob/0ffe9c8d77ef09a9deee534989e30367f3072cd3/src/SearchPath.hh#L48)

**Comment by lvanengelen** [comment]
I also tried to get Nix to work with `j4-dmenu-desktop` and found that when I set `XDG_DATA_DIRS=$HOME/.nix-profile/share:/usr/share` the desktop entry in `/usr/share/applications` is found. After adding `.nix-profile` to the _end_ of `XDG_DATA_DIRS` the correct entry was found. So it seems that later path entries are preferred to earlier ones. 

If @Lykos153 got wrong (global) entries instead of no entries, this could be the same problem.

**Comment by meator** [comment]
`$XDG_DATA_DIRS` and `$XDG_DATA_HOME` are honored. Precedence is handled from left to right (the first directory in `$XDG_DATA_DIRS` overrides the second directory in it if a conflict arises). If you believe that some desktop files are still missing, feel free to reopen this issue (or comment on it).

Note that large parts of j4-dmenu-desktop got rewritten since the last release was made. It is possible that the behavior in `develop` differs from `r2.18`. If they diverge, the `develop` behavior should hopefully be the correct one. I have paid very close attention to freedesktop specifications while rewriting the code. I am planning to make a new release in the foreseeable future.<sup>no promisses or ETAs though</sup>
