### ISSUE TITLE
Error when building makepkg -si: 

### ISSUE THREAD

**Issue by boban-dj** [enkore/j4-dmenu-desktop#120]
Anybody an idea why the package wants to add key to root/.ssh/known_hosts?
I have the github RSA key in my $USER/.ssh/known_hosts
When I remove the user know_hosts file it adds the key fine, but then it asks for adding to root. Ofcourse it cannot add and makepkg cannot run as root.

        [ 25%] Performing update step for 'catch'
	hostkeys_find_by_key_hostfile: hostkeys_foreach failed for /root/.ssh/known_hosts: Permission denied
	The authenticity of host 'github.com (140.82.121.4)' can't be established.
	RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
	This key is not known by any other names
	Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
	Could not stat /root/.ssh: Permission denied
	Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
	git@github.com: Permission denied (publickey).
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.
	make[2]: *** [CMakeFiles/catch.dir/build.make:124: catch/src/catch-stamp/catch-update] Error 1
	make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/catch.dir/all] Error 2
	make: *** [Makefile:146: all] Error 2
	==> ERROR: A failure occurred in package().
	    Aborting...

**Comment by meator** [comment]
I don't think this is a j4-dmenu-desktop specific issue. It could be related to `makepkg`. If you suspect it **is** a j4-dmenu-desktop issue, feel free to reopen this PR.

CMakeLists.txt never used SSH to pull dependencies to my knowledge. git pulls were (and are) done using HTTPS. Because of this, I believe that the build system could have been modified or this is `makepkg` specific.
