### ISSUE TITLE
Cannot open display error

### ISSUE THREAD

**Issue by dajix350** [enkore/j4-dmenu-desktop#134]
When I try to start j4-dmenu-desktop via the command line, I get the error
```
Read 19 .desktop files, found 16 apps.
cannot open display
```
I am using Sway on Arch Linux. I installed j4-dmenu-desktop via the AUR, and have not made any major changes to the system. My default terminal is foot.

**Comment by meator** [comment]
Is Your `$DISPLAY` environmental variable properly set?

Does
```sh
echo a | dmenu
```
work in Your shell?

**Comment by dajix350** [comment]
Sorry, this is my first time using Arch. I know how to set environment variables, but I don't know what to set `$DISPlAY` to. All I can find is a Arch forums post asking for help on setting that variable where people argued about whether setting variables in .bashrc was good practice without giving an answer. From what I can gather, `$DISPLAY` is an xorg variable, and I am using Sway (Wayland). 

That command gives the same `cannot open display` error.

**Comment by meator** [comment]
This environmental variable is Xorg specific (I think, I don't know wayland). It is usually set to `:0`.

The fact that the second command failed shows that this isn't a problem with j4-dmenu-desktop but with dmenu.

J4-dmenu-desktop doesn't make the menu itself, it just collects desktopfile data and then it pipes them into dmenu which prompts the user for their choice.

I think the problem is that dmenu works only in Xorg.

But there is a solution: j4dd doesn't require dmenu, it just requires a program that behaves like dmenu (but it uses dmenu by default). You could use something like https://github.com/nyyManni/dmenu-wayland instead of dmenu. You can then do
```sh
j4-dmenu-desktop --dmenu="dmenu-wl -i"
```
to use the desired dmenu alternative.

I haven't tested this. I do not know if dmenu-wayland is compatible with dmenu (but it should be if it has "dmenu" in its name). I myself use Xorg so I never had problems with this.

**Comment by dajix350** [comment]
For people looking here in the future, an easy solution is installing `xwayland` (`xorg-xwayland` on the Arch extras repo) and adding `xwayland enable` to your sway config file.
