### ISSUE TITLE
.desktop file Exec escaping not working anymore

### ISSUE THREAD

**Issue by Hornobster** [enkore/j4-dmenu-desktop#175]
I have this .desktop file for a specific Brave profile:

```
[Desktop Entry]
Version=1.0
Name=Brave 4BMC
StartupNotify=true
StartupWMClass=brave-browser-4bmc
TryExec=brave
Exec=brave --profile-directory=\"Profile 1\" --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto %U
Terminal=false
Icon=brave
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
```

Since last release I am getting an error when launching j4-dmenu-desktop:

```console
$ j4-dmenu-desktop --dmenu="bemenu -H22 -i" --no-exec

[2024-08-04 18:31:23.846] [error] [Application.cc:128] /home/user/.local/share/applications/brave-browser-4bmc.desktop: Exec: Tried to interpret invalid escape sequence \".

terminate called after throwing an instance of 'escape_error'
  what():  Exec: Tried to interpret invalid escape sequence \".
Aborted (core dumped)
```

I have solved this with:
```
Exec=brave --profile-directory='"Profile 1"' --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto %U
```

I'm writing this issue because I haven't seen anything related to this change in the release notes.

**Comment by meator** [comment]
Your original desktop file is not conformant to the [Desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/1.5/) (namely the [quoting Exec](https://specifications.freedesktop.org/desktop-entry-spec/1.5/exec-variables.html) part). j4-dmenu-desktop cannot promise support for desktop files which do not adhere to the spec. A conformant Exec key would look something like this:

```ini
Exec=brave "--profile-directory=Profile 1" --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto %U
```

Even though I don't consider this a "breaking change", I will update the release notes of r3.1 to warn users about using nonconformant desktop files, because version r3.1 introduces a more strict handling of desktop files.

I will update the [GitHub release description](https://github.com/enkore/j4-dmenu-desktop/releases/tag/r3.1), but I don't think it's necessary to update the [CHANGELOG](https://github.com/enkore/j4-dmenu-desktop/blob/develop/CHANGELOG) (but I'm open to discussion).

**Comment by Hornobster** [comment]
Unfortunately that doesn't work, but maybe it's because I pass the output to swaymsg?

In my sway config I have:
```
set $menu j4-dmenu-desktop --dmenu="bemenu -H22 -i" --no-exec | xargs swaymsg exec --
```

Is my solution above conformant to the spec?

EDIT: yes, I can confirm that your Exec works without `--no-exec | xargs swaymsg exec --`

**Comment by meator** [comment]
j4-dmenu-desktop has support for Sway. Try running

```
j4-dmenu-desktop <args> --i3-ipc
```

**Comment by Hornobster** [comment]
Thank you, that works.
