### ISSUE TITLE
what():  Malformed file

### ISSUE THREAD

**Issue by Rojikku** [enkore/j4-dmenu-desktop#190]
Version: 3.1-3 off extra

Probably literally #176 as I solved it with that. I just wanted to provide you with a problem-child `.desktop` to experiment with in fixing the issue.

Note: I swear this wasn't an issue in older versions of j4, and irony doesn't seem to have changed recently, so possibly a regression of some form?

` aurto irony-mod-manager-bin 1.26.201-1 [installed]` appears to be the problem child for me. I have copied the desktop file, added .txt to the end, and uploaded it, so it *should* capture any strange characters within the file still.

[irony-mod-manager-bin.desktop.txt](https://github.com/user-attachments/files/18133175/irony-mod-manager-bin.desktop.txt)

**Comment by meator** [comment]
Fixed in [r3.2 release](https://github.com/enkore/j4-dmenu-desktop/releases/tag/r3.2) (latest release). The handling of invalid desktop files was changed in the latest release, they are handled more gracefully now. When an invalid desktop file is encountered, j4-dmenu-desktop prints a warning and it skips the desktop file.

The desktop file is provided directly by the `irony-mod-manager-bin` AUR package, so the AUR is at fault for this. I have reported this to the package maintainer: https://aur.archlinux.org/packages/irony-mod-manager-bin#comment-1002157

The faulty file is here (for future reference): https://aur.archlinux.org/cgit/aur.git/tree/irony-mod-manager-bin.desktop?h=irony-mod-manager-bin&id=5cf76a0bdda10eb77083ea1e794570740f51aef3

I have also flagged Arch Linux's j4-dmenu-desktop package as out-of-date.

I am not an Arch Linux user, so I will not pursue this issue further and will leave it to the respective package maintainers.

If the desktop file is located in `/usr/share/aplications/`, you can most likely solve the problem by copying `/usr/share/aplications/irony-mod-manager-bin.desktop` to `~/local/share/applications/irony-mod-manager-bin.desktop` and then deleting the last blank line of `~/local/share/applications/irony-mod-manager-bin.desktop`. The `.local/` directory has a higher priority than system directories, so a desktop file with the same name in `.local/share/applications/` will take precedence over `/usr/share/applications`.

The rules may differ if your desktop file is located somewhere else. Please read the j4-dmenu-desktop manpage for more info (especially the `ENVIRONMENT` section).

---

> Version: 3.1-3 off extra

Version `3.1-3` is not a valid j4-dmenu-desktop version. Please use `j4-dmenu-desktop --version` to determine the version. The `-3` suffix is specific to Arch Linux and is not related to j4-dmenu-desktop (this is not that big of an issue, but it could help you with writing future bug reports to j4-dmenu-desktop or to other projects).

Please also state the Linux distro you are using when reporting bugs. I was able to infer that you are using Arch Linux. This is particularly relevant to this issue, because it originates from the AUR.

I could create an issue template for these things.

**Comment by Zetabite** [comment]
Issue is fixed now on the AUR package. Do note, if you use any package older than 1.26.201-2, the issue will persist. You will have to manually fix it in that case.

**Comment by meator** [comment]
The Arch Linux package of j4-dmenu-desktop was updated, which means that desktop files like the one in this issue will give users a warning message with the filename, line number and the description of the error instead of aborting with a generic error message.

@Zetabite Thank you for your swift response!
