### ISSUE TITLE
Error building in Arch/Manjaro

### ISSUE THREAD

**Issue by concatime** [enkore/j4-dmenu-desktop#71]
Hi. I'm having some issues while compiling the app. I tried with AUR package and manually compiling, but with the same result. Maybe I'm missing some dependencies?
[log.txt](//github.com/enkore/j4-dmenu-desktop/files/1447918/log.txt)

**Comment by concatime** [comment]
Moreover, the link [above](//github.com/enkore/j4-dmenu-desktop#archlinux) is returning a gentle 404 page.

**Comment by Zetten** [comment]
I think the problem is that this project's CMakeLists.txt is pulling in the master branch of `https://github.com/philsquared/Catch.git`, which now redirects to `https://github.com/catchorg/Catch2` and the Catch includes have moved around between 1.x and 2.x.

I simply added `GIT_TAG Catch1.x` to the `ExternalProject_Add` call to grab the 1.x branch and it seems to build and install fine.

This is okay for a local workaround, but I guess for a PR the project would prefer a more concrete declaration of the specific release of Catch it depends on, and I'm not familiar enough with cmake or this project to figure that out.

**Comment by concatime** [comment]
Thank you! I posted a pull request ;)
I need you to support this PR.

**Comment by concatime** [comment]
It would be really cool if someone migrate this project to Carch2 and implements Ninja into the build!
*I don't have the knowledge to do what I suggest

**Comment by bobvdvalk** [comment]
Indeed I am having the same problem right now.

**Comment by enkore** [comment]
I just tagged and signed r2.16

**Comment by enkore** [comment]
Fake-edit: I'll just mark 2019 in my calendar to tag 2.17 :)
