### ISSUE TITLE
Terminal app outputs escape sequence

### ISSUE THREAD

**Issue by Scriptim** [enkore/j4-dmenu-desktop#77]
I have a `.desktop` file that runs `android-file-transfer` (Arch Linux) with `Terminal=True`.

When I run it directly from the terminal it outputs `upload worker started`, but when I run it from `j4-dmenu-desktop` a terminal window opens with the following output:

`\033]2;Android File Transfer (MTP)\007upload worker started`

(`android-file-transfer` is just an example, it is the same with other terminal applications)

From what I understand this is supposed to set the title of the terminal (it actually does), but why is it written to the output?

I'm not entirely sure whether this is a `j4-dmenu-desktop` issue.

**Comment by dgaw** [comment]
The issue seems to be caused by this line:
https://github.com/enkore/j4-dmenu-desktop/blob/master/src/ApplicationRunner.hh#L63

I'm not sure why this is called twice, with and without -e. In my version of echo only calling it with -e causes the escape sequences to be evaluated.

Anyway, I commented out the line above and recompiled. The redundand output is gone.
