### ISSUE TITLE
Keep j4-dmenu-desktop running in the background

### ISSUE THREAD

**Issue by dgaw** [enkore/j4-dmenu-desktop#79]
First of all, thanks @enkore for a great piece of software! I really enjoy proper .desktop file support and the startup time.

Having said that, I think it would be great to have an option to keep j4-dmenu-desktop running in the background to improve responsiveness even more. I'm suggesting this because I've noticed that if the hard disk is a little busy it does take a while for the menu to load.

What do you think?

**Comment by enkore** [comment]
The IPC is the hardest part of this, the changes in the code should be relatively few and limited. I think the easiest way may be a named pipe, since it's portable (Linux and BSDs) and we only need to communicate "do something", like so:

```
j4-dmenu-desktop --wait-on ~/.j4ddfifo
```

Then j4dd would fork and spawn a dmenu every time j4ddfifo becomes readable. Then, in turn, something like 

```
echo > ~/.j4ddfifo
```

can be bound in the window manager.

**Comment by enkore** [comment]
#80
